### ISSUE TITLE
Accept requestID as a string

### ISSUE THREAD

**Issue by ricantech** [modelcontextprotocol/kotlin-sdk#25]
When mcp server used with https://github.com/spring-projects-experimental/spring-ai-mcp the RequestID on the mentioned repo is defined as 
```
	private String generateRequestId() {
		return this.sessionPrefix + "-" + this.requestCounter.getAndIncrement();
	}
``` 
(source: https://github.com/spring-projects-experimental/spring-ai-mcp/blob/main/spring-ai-mcp-core/src/main/java/org/springframework/ai/mcp/spec/DefaultMcpSession.java#L205)

If I understand MCP definition correctly the schema defines ID as  a `string` or an `integer`
(source: https://github.com/modelcontextprotocol/specification/blob/main/schema/schema.json#L1468)

## Example

When request is generated by spring-ai-mcp it looks as follows
```
{
  "jsonrpc": "2.0",
  "method": "initialize",
  "id": "ebf9f64a-0",
  "params": {
    "protocolVersion": "2024-11-05",
    "capabilities": {},
    "clientInfo": {
      "name": "mcp-java-client",
      "version": "0.2.0"
    }
  }
}
```

which complies with specified schema, but when it's received on MCP server (created through SDK) deserialization to `JSONRPCRequest` fails due to the fact that expected type of `id` is `Long`

## Expected solution

SDK should comply with specification and allow RequestID to be defined as `string` or `integer`

## Additional information

Personally I don't understand how the incrementation of string values is expected but with IDs as shared above it seems to be possible tho expect this given format would introduce tight coupliing with spring-ai-mcp implementation so not really sure how to tackle this

**Comment by ignatov** [comment]
Hi! Thanks for the report and for using the library. Working on the issue, please see [29ef829](https://github.com/modelcontextprotocol/kotlin-sdk/commit/29ef82961eb48727e7c591f6df2b0164d6f43b1f)

**Comment by ricantech** [comment]
Thank you for quick action!

**Comment by ignatov** [comment]
please checkout 0.2.0 version
