### ISSUE TITLE
Fix the difference in error handling between Kotlin and Typescript implementations in onClose

### ISSUE THREAD

**Issue by e5l** [modelcontextprotocol/kotlin-sdk#3]
**Describe the bug**

The difference in error handling between Kotlin and Typescript implementations in onClose:

```
private fun onClose() {
        val error = McpError(ErrorCode.Defined.ConnectionClosed.code, "Connection closed")
        for (handler in responseHandlers.values) {
            handler(null, error)
        }

        responseHandlers.clear()
        progressHandlers.clear()
        transport = null
        onclose()
    }

Typescript Protocol

private _onclose(): void {
    const responseHandlers = this._responseHandlers;
    this._responseHandlers = new Map();
    this._progressHandlers.clear();
    this._transport = undefined;
    this.onclose?.();

    const error = new McpError(ErrorCode.ConnectionClosed, "Connection closed");
    for (const handler of responseHandlers.values()) {
      handler(error);
    }
  }
```

**Comment by ignatov** [comment]
fixed

**Comment by thevoiceless** [comment]
@ignatov I don't believe this was fixed correctly; the `responseHandlers` map is [cleared](https://github.com/modelcontextprotocol/kotlin-sdk/blob/main/src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/Protocol.kt#L176) before [iterating over it](https://github.com/modelcontextprotocol/kotlin-sdk/blob/main/src/commonMain/kotlin/io/modelcontextprotocol/kotlin/sdk/shared/Protocol.kt#L182), without making a local copy first. If the goal is to mimic the TS shown above, it would need to be something like
```kt
private fun doClose() {
  val responseHandlersCopy = responseHandlers.toMutableMap()
  // ...
  for (handler in responseHandlersCopy.values) {
    handler(null, error)
  }
```
